import { moduleLabel } from '@/features/module/mockModules';

export const MOCK_EXAMS = [
  { id: 'EX-8201', title: 'ML Fundamentals — Final Examination', subject: 'Machine Learning', course: 'Machine Learning Fundamentals', moduleId: 'mod-3', module: moduleLabel('mod-3'), questions: 45, duration: 90, passMark: 70, status: 'Published', attempts: 1247, updated: '2h ago' },
  { id: 'EX-8200', title: 'Deep Learning Midterm', subject: 'Deep Learning', course: 'Deep Neural Networks', moduleId: 'mod-4', module: moduleLabel('mod-4'), questions: 32, duration: 75, passMark: 65, status: 'Published', attempts: 863, updated: '1d ago' },
  { id: 'EX-8199', title: 'Statistics Quiz 4', subject: 'Statistics', course: 'Statistics for ML', moduleId: 'mod-9', module: moduleLabel('mod-9'), questions: 20, duration: 45, passMark: 60, status: 'Draft', attempts: 0, updated: '3h ago' },
  { id: 'EX-8198', title: 'Python Basics Final', subject: 'Programming', course: 'Python for Data Science', moduleId: 'mod-6', module: moduleLabel('mod-6'), questions: 50, duration: 120, passMark: 70, status: 'Published', attempts: 2054, updated: '5d ago' },
  { id: 'EX-8197', title: 'Neural Networks Quiz 2', subject: 'Neural Nets', course: 'Deep Neural Networks', moduleId: 'mod-5', module: moduleLabel('mod-5'), questions: 15, duration: 30, passMark: 75, status: 'Archived', attempts: 421, updated: '2w ago' },
  { id: 'EX-8196', title: 'Supervised Learning Quiz 1', subject: 'Machine Learning', course: 'Machine Learning Fundamentals', moduleId: 'mod-2', module: moduleLabel('mod-2'), questions: 25, duration: 60, passMark: 65, status: 'Published', attempts: 512, updated: '4h ago' },
  { id: 'EX-8195', title: 'Foundations of ML — Module Test', subject: 'Machine Learning', course: 'Machine Learning Fundamentals', moduleId: 'mod-1', module: moduleLabel('mod-1'), questions: 30, duration: 60, passMark: 60, status: 'Published', attempts: 389, updated: '1d ago' },
  { id: 'EX-8194', title: 'Data Wrangling Practical', subject: 'Programming', course: 'Python for Data Science', moduleId: 'mod-7', module: moduleLabel('mod-7'), questions: 20, duration: 90, passMark: 70, status: 'Published', attempts: 674, updated: '2d ago' },
  { id: 'EX-8193', title: 'Descriptive Statistics Midterm', subject: 'Statistics', course: 'Statistics for ML', moduleId: 'mod-8', module: moduleLabel('mod-8'), questions: 40, duration: 90, passMark: 65, status: 'Published', attempts: 932, updated: '3d ago' },
  { id: 'EX-8192', title: 'Hypothesis Testing Quiz', subject: 'Statistics', course: 'Statistics for ML', moduleId: 'mod-9', module: moduleLabel('mod-9'), questions: 18, duration: 40, passMark: 60, status: 'Draft', attempts: 0, updated: '6h ago' },
  { id: 'EX-8191', title: 'Regularization Techniques Quiz', subject: 'Machine Learning', course: 'Machine Learning Fundamentals', moduleId: 'mod-3', module: moduleLabel('mod-3'), questions: 22, duration: 45, passMark: 70, status: 'Published', attempts: 748, updated: '1d ago' },
  { id: 'EX-8190', title: 'Backpropagation & Training Quiz', subject: 'Neural Nets', course: 'Deep Neural Networks', moduleId: 'mod-4', module: moduleLabel('mod-4'), questions: 16, duration: 35, passMark: 65, status: 'Published', attempts: 589, updated: '4d ago' },
  { id: 'EX-8189', title: 'Normalization & Architectures Test', subject: 'Neural Nets', course: 'Deep Neural Networks', moduleId: 'mod-5', module: moduleLabel('mod-5'), questions: 28, duration: 70, passMark: 70, status: 'Draft', attempts: 0, updated: '8h ago' },
  { id: 'EX-8188', title: 'Python Syntax Check — Practice', subject: 'Programming', course: 'Python for Data Science', moduleId: 'mod-6', module: moduleLabel('mod-6'), questions: 15, duration: 30, passMark: 50, status: 'Published', attempts: 1204, updated: '1w ago' },
  { id: 'EX-8187', title: 'Model Evaluation Final', subject: 'Machine Learning', course: 'Machine Learning Fundamentals', moduleId: 'mod-2', module: moduleLabel('mod-2'), questions: 45, duration: 100, passMark: 75, status: 'Archived', attempts: 310, updated: '3w ago' },
];